### ISSUE TITLE
widget freezes browser

### ISSUE THREAD

**Issue by karser** [erxes/erxes-widgets#113]
Hello,
I launched `erxes/erxes-widgets:develop-latest` using docker. The admin panel works fine but after I installed widget, my browser started freezing. When I click on the input area or start typing the widget produces 100s of requests each time. I tested this in chromium and firefox, all the same. 
The request payload is the same all the time:
```
POST http://localhost:3100/graphql
{"operationName":"readConversationMessages","variables":{"conversationId":"JLNPcDjQLuxdS26xc"},"query":"mutation readConversationMessages($conversationId: String) {\n  readConversationMessages(conversationId: $conversationId)\n}\n"}
```
I recorded a video that demonstrates the issue
https://www.youtube.com/watch?v=xIy9IAFUvdQ

**Comment by batamar** [comment]
@karser Thanks for the feedback. Let me check

**Comment by batamar** [comment]
@karser Can I have your mongodb dump files ?. It will help a lot.

**Comment by karser** [comment]
Sure, here is my mongodb docker volume [mongodata.tar.gz](https://github.com/erxes/erxes-widgets/files/2956491/mongodata.tar.gz)
You can plug it the standard way:
```
    mongo:
        image: mongo:3.6
        container_name: mongo
        ports:
            - "27017:27017"
        networks:
            - erxes-net
        volumes:
            - ./mongodata:/data/db
```

I did docker-compose pull and then down & up, the issue persisted.
Also, I tried deploying widget on http/https, still no luck.
